import { useState, useEffect } from 'react';

// Spanish governance briefings generated by the KarmaKadabra pipeline
// (karmakadabra: plans/ULTRAVIOLETA_INTELLIGENCE_ENGINE_MASTER_PLAN.md, F1-3).
// Static public JSON, refreshed out-of-band; treat as external data.
const BRIEFINGS_URL =
  'https://ultravioletadao.s3.us-east-1.amazonaws.com/governance/briefings.json';

let cachedPromise = null;

const loadBriefings = () => {
  if (!cachedPromise) {
    cachedPromise = fetch(BRIEFINGS_URL)
      .then((res) => (res.ok ? res.json() : null))
      .then((data) => {
        const byId = {};
        (data?.briefings || []).forEach((b) => {
          if (b?.id) byId[b.id] = b;
        });
        return byId;
      })
      .catch(() => ({}));
  }
  return cachedPromise;
};

/** Returns the briefing object for a proposal id, or null while loading/missing. */
const useGovernanceBriefing = (proposalId) => {
  const [briefing, setBriefing] = useState(null);

  useEffect(() => {
    let alive = true;
    if (!proposalId) return undefined;
    loadBriefings().then((byId) => {
      if (alive) setBriefing(byId[proposalId] || null);
    });
    return () => {
      alive = false;
    };
  }, [proposalId]);

  return briefing;
};

export default useGovernanceBriefing;
